config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end

  delete '/doses/:id', to: 'doses#destroy', as: 'dose'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true, allow_blank: false
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates_uniqueness_of :cocktail, scope: :ingredient

  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses
  has_many :cocktails, through: :doses

  before_destroy :check_for_cocktails

  private

  def check_for_cocktails
    return true unless cocktails.count.positive?

    # errors.add_to_base('cannot delete ingredient while linked cocktails exist')
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredients = Ingredient.all
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail_id = params[:cocktail_id]
    if @dose.save
      redirect_to cocktail_path(params[:cocktail_id])
    else
      render :new
    end
  end

  def destroy
    dose = Dose.find(params[:id])
    cocktail = dose.cocktail
    dose.destroy
    redirect_to cocktail_path(cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1 class="title">All Cocktails</h1>

<div class="columns is-multiline">
  <% @cocktails.each do |cocktail| %>

  <div class="column is-one-quarter">
    <%= link_to cocktail_path(cocktail) do%>
    <div class="dan-card" style="background-image: url('<%= cl_image_path(cocktail.photo, :height => 350, :crop => :fill, :secure=>true)  %>');">
      <h2 class="dan-card-title is-size-3 has-text-dark has-text-weight-bold"><%= cocktail.name %></h2>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="columns">
  <div class="column is-half is-offset-one-quarter">
  <h1 class="title">Add a new cocktail</h1>
  <%= form_for(@cocktail) do |f| %>
    <div class="field">
      <label class="label"><%= f.label :name, class: 'label' %></label>
      <div class="control">
        <%= f.text_field :name, class: 'input' %>
      </div>
    </div>
    <div class="field">
      <div class="file has-name">
        <label class="file-label">
          <%= f.file_field :photo, class: 'file-input' %>
          <%= f.hidden_field :photo_cache, as: :hidden %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
              Add a picture…
            </span>
          </span>
          <span class="file-name">
            no image selected
          </span>
        </label>
      </div>
    </div>
    <div class="field">
      <%= f.submit class: 'button is-primary' %>
    </div>
  <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><%= link_to 'all cocktails', cocktails_path  %></li>
    <li class="is-active"><a href="#" aria-current="page"><%= @cocktail.name %></a></li>
  </ul>
</nav>

<h1 class="title"><%= @cocktail.name %></h1>

<div class="columns">
  <div class="column">
    <%= cl_image_tag @cocktail.photo %>
  </div>
  <div class="column">
  <table class="table is-striped">
    <thead>
      <tr>
        <th>Amount:</th>
        <th>Ingredient:</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @cocktail.doses.each do |dose| %>
      <tr>
        <td><%= dose.description %></td>
        <td><%= dose.ingredient.name %></td>
        <td>
          <%= link_to dose_path(dose), method: :delete do  %>
            <span class="icon has-text-danger">
              <i class="fas fa-trash"></i>
            </span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Add dose',  new_cocktail_dose_path(@cocktail), class: 'button is-primary'%>
  </div>
</div>

app/views/doses/new.html.erb
<div class="columns">
  <div class="column is-half is-offset-one-quarter">
  <h1 class="title">Add a dose to <%= @cocktail.name %></h1>
  <%= form_for([@cocktail, @dose]) do |f| %>
    <div class="field">
      <label class="label"><%= f.label :description, class: 'label' %></label>
      <div class="control">
        <%= f.text_field :description, class: 'input' %>
      </div>
    </div>
    <div class="field">
      <label class="label"><%= f.label :ingredient_id, class: 'label' %></label>
      <div class="control">
        <div class="select is-primary">
          <%= f.select :ingredient_id do %>
            <%= options_from_collection_for_select(@ingredients, :id, :name) %>
          <% end %>
        </div>
      </div>
    </div>
    <%= f.submit class: 'button is-primary' %>
  <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/cocktails">
      <span class="has-text-primary is-size-2"><i class="fas fa-glass-martini"></i> Mr Cocktail</span>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to 'Home', cocktails_path, class: 'navbar-item'  %>

    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to 'New Cocktail', new_cocktail_path, class: 'button is-primary'  %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_pack_tag "application" %>
  </body>
</html>